version: '2'
services:
  nginx:
    build: ./docker/nginx 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/conf:/etc/nginx
      - ./www:/var/www
  php-fpm:
    build: ./docker/php
    ports:
      - "9001:9000"
    volumes:
      - ./www:/var/www
  mysql:
    image: mysql
    ports:
      - "3305:3306"
    environment:
      - MYSQL_DATABASE=blog
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./data/mysql:/var/lib/mysql
  redis:
    build: ./docker/redis
  #image: redis
    ports:
      - "16379:6379"
    volumes:
      - ./data/redis:/data
      - ./docker/redis/redis.conf:/etc/redis/redis.conf  
